apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: myapp.local  # Your hostname or domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: check-duplicate-svc
                port:
                  number: 80
